Fix NameError in a test in switch_mod.utilities
Change 94e732c2528621649ff16c6e6eeb3325f69ad71c caused a doctest in
utilities.py to fail with:
  NameError: name 'utilities' is not defined